from robot import run
import os
from bs4 import BeautifulSoup
from datetime import datetime

# Run Robot Framework tests
test_results_dir = 'test_results'
run('test.robot', outputdir=test_results_dir)

# Parse the output XML file generated by Robot Framework
result_file = os.path.join(test_results_dir, 'output.xml')
with open(result_file, 'r') as f:
    soup = BeautifulSoup(f, 'xml')

# Extract test results and timestamps
tests = soup.find_all('test')
start_time = soup.find('suite')['starttime']
end_time = soup.find('suite')['endtime']

# Read the version information from the text file
with open('DB_file/version_info.txt', 'r') as f:
    version_info = f.read()

# Convert timestamps to readable format
start_time = datetime.strptime(start_time, "%Y%m%d %H:%M:%S.%f").strftime("%Y-%m-%d %H:%M:%S")
end_time = datetime.strptime(end_time, "%Y%m%d %H:%M:%S.%f").strftime("%Y-%m-%d %H:%M:%S")

# Calculate elapsed time
elapsed_time = (datetime.strptime(end_time, "%Y-%m-%d %H:%M:%S") - datetime.strptime(start_time, "%Y-%m-%d %H:%M:%S"))

# Generate HTML report
html_content = f'''
<!DOCTYPE html>
<html>
<head>
    <title>QuickStart Test Report for NS CDC STD</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
        }}
        h1, h2, h3 {{
            color: #4F8A10;
        }}
        .summary, .statistics, .details {{
            border: 1px solid #D6D6D6;
            padding: 10px;
            margin: 20px 0;
        }}
        .summary table, .statistics table, .details table {{
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }}
        .summary th, .statistics th, .details th {{
            background-color: #8B4513;
            color: white;
            border: 1px solid black;
            padding: 5px;
        }}
        .summary td, .statistics td, .details td {{
            border: 1px solid black;
            padding: 5px;
        }}
    </style>
</head>
<body>
    <h1>QuickStart Test Report for NS CDC STD</h1>
    <div class="summary">
        <h2>Summary Information</h2>
        <table>
            <tr>
                <th>Status</th>
                <td>All tests passed</td>
            </tr>
            <tr>
                <th>Start Time</th>
                <td>{start_time}</td>
            </tr>
            <tr>
                <th>End Time</th>
                <td>{end_time}</td>
            </tr>
            <tr>
                <th>Elapsed Time</th>
                <td>{elapsed_time}</td>
            </tr>
            <tr>
                <th>SW Version</th>
                <td>{version_info}</td>
            </tr>
        </table>
    </div>
    <div class="statistics">
        <h2>Test Statistics</h2>
        <h3>Total Statistics</h3>
        <table>
            <tr>
                <th>Total</th>
                <th>Pass</th>
                <th>Fail</th>
                <th>Elapsed</th>
                <th>Pass / Fail</th>
            </tr>
            <tr>
                <td>{len(tests)}</td>
                <td>{len(tests)}</td>
                <td>0</td>
                <td>{elapsed_time}</td>
                <td>{len(tests)} / 0</td>
            </tr>
        </table>
    </div>
    <div class="details">
        <h2>Test Details</h2>
        <table>
            <tr>
                <th>Testcase</th>
                <th>Result</th>
                <th>Remark</th>
            </tr>
'''

# Populate table with test results
for test in tests:
    name = test['name']
    status = test.find('status')['status']
    html_content += f'''
        <tr>
            <td>{name}</td>
            <td>{status}</td>
            <td></td>
        </tr>
    '''

html_content += '''
        </table>
    </div>
</body>
</html>
'''

# Save HTML to file
with open('report.html', 'w') as f:
    f.write(html_content)